"""Golden-set value objects.

Two decisions shape everything here.

**Labels are character spans into the normalized document, never chunk ids**
(ADR-0002). Chunk-id labels would be invalidated by any chunking change, which
would make the chunk-size comparison -- the project's headline experiment --
literally impossible to run.

**Relevance is graded 0-3** (ADR-0004). Recall binarizes at ``gain >= 2`` to
stay interpretable; nDCG uses the full grade.

Each record also carries its provenance, because the report breaks results
down by human-authored versus LLM-proposed origin, and a large gap there would
itself be a finding.
"""

from __future__ import annotations

import hashlib
import re
from collections import Counter
from typing import Final, Literal, Self

from pydantic import Field, model_validator

from groundtruth.config.hashing import canonical_json
from groundtruth.frozen import FrozenModel

QueryCategory = Literal[
    "factual-lookup",
    "multi-hop",
    "negation-exclusion",
    "procedural",
    "ambiguous-terminology",
]

#: Declared explicitly as well as in the type, so the set is iterable at
#: runtime -- reporting needs to show a category with zero queries, and a
#: category that is simply absent reads as zero only to someone who already
#: knew to look for it.
CATEGORIES: Final[tuple[QueryCategory, ...]] = (
    "factual-lookup",
    "multi-hop",
    "negation-exclusion",
    "procedural",
    "ambiguous-terminology",
)

#: Recall counts a span as relevant at or above this gain (ADR-0004).
MIN_RELEVANT_GAIN: Final[int] = 2

#: Highest gain in the rubric: dispositive.
MAX_GAIN: Final[int] = 3

_WHITESPACE = re.compile(r"\s+")


def normalize_query(query: str) -> str:
    """Fold a query to the form duplicate detection compares.

    Case and internal spacing only. Nothing semantic: two genuinely different
    phrasings of one question are a judgment call for the reviewer, not
    something to resolve silently in a validator.
    """
    return _WHITESPACE.sub(" ", query).strip().casefold()


class RelevanceLabel(FrozenModel):
    """One labeled span of one document.

    ``quote`` is redundant with the span *by design*. It is the integrity
    check that catches corpus re-normalization drift immediately, instead of
    as an unexplained metric shift weeks later: if the document text ever
    stops matching the quote at those offsets, every label pointing into that
    document is suspect and the validation run says so.
    """

    doc_id: str = Field(min_length=1)
    #: Offsets into the NORMALIZED document text.
    char_start: int = Field(ge=0)
    char_end: int = Field(ge=0)
    #: 0 not relevant · 1 partial · 2 relevant · 3 dispositive.
    gain: int = Field(ge=0, le=MAX_GAIN)
    quote: str

    @model_validator(mode="after")
    def _span_and_quote_must_agree(self) -> Self:
        if self.char_end <= self.char_start:
            raise ValueError(
                f"char_end ({self.char_end}) must be greater than char_start ({self.char_start})"
            )
        if len(self.quote) != self.char_end - self.char_start:
            raise ValueError(
                f"quote is {len(self.quote)} characters but the span covers "
                f"{self.char_end - self.char_start}; the quote must be exactly "
                f"doc_text[char_start:char_end]"
            )
        return self

    @property
    def is_relevant(self) -> bool:
        """Whether Recall counts this span. nDCG uses ``gain`` directly."""
        return self.gain >= MIN_RELEVANT_GAIN

    @property
    def span_key(self) -> tuple[str, int, int]:
        return (self.doc_id, self.char_start, self.char_end)


class Provenance(FrozenModel):
    """Where a pair came from and who signed off on it.

    Every field here exists to make a specific claim checkable. Without
    ``origin`` the human-versus-LLM breakdown is impossible; without
    ``generator_model`` and ``prompt_version`` "generated by a model" is
    unfalsifiable; without ``reviewer`` the human-review claim of ADR-0009 is
    just an assertion.
    """

    origin: Literal["human", "llm"]
    #: Pinned snapshot id. Required for, and only for, LLM-proposed pairs.
    generator_model: str | None = None
    prompt_version: str | None = None
    source_candidate_id: str | None = None

    reviewer: str = Field(min_length=1)
    reviewed_at: str = Field(min_length=1)
    review_action: Literal["accepted", "edited"]
    #: Which fields the reviewer changed. Required when the action is "edited".
    edited_fields: tuple[str, ...] = ()
    review_seconds: float | None = Field(default=None, ge=0.0)

    @model_validator(mode="after")
    def _origin_must_match_its_generator_fields(self) -> Self:
        if self.origin == "llm":
            if not self.generator_model:
                raise ValueError("generator_model is required when origin is 'llm'")
            if not self.prompt_version:
                raise ValueError("prompt_version is required when origin is 'llm'")
            return self

        if self.generator_model or self.prompt_version:
            raise ValueError(
                "a human-authored pair must not name a generator_model or "
                "prompt_version; the origin breakdown in the report depends on "
                "these being mutually exclusive"
            )
        return self

    @model_validator(mode="after")
    def _action_must_match_its_edits(self) -> Self:
        if self.review_action == "edited" and not self.edited_fields:
            raise ValueError(
                "review_action 'edited' requires edited_fields; an edit that "
                "names nothing is indistinguishable from an acceptance"
            )
        if self.review_action == "accepted" and self.edited_fields:
            raise ValueError(
                f"review_action 'accepted' must not list edited_fields, got {self.edited_fields!r}"
            )
        return self


class GoldenPair(FrozenModel):
    """One query and every span judged against it."""

    query_id: str = Field(min_length=1)
    query: str = Field(min_length=1)
    category: QueryCategory
    labels: tuple[RelevanceLabel, ...]
    provenance: Provenance

    @model_validator(mode="after")
    def _query_must_not_be_blank(self) -> Self:
        if not self.query.strip():
            raise ValueError("query must contain something other than whitespace")
        return self

    @model_validator(mode="after")
    def _labels_must_be_unique_and_canonically_ordered(self) -> Self:
        if not self.labels:
            raise ValueError("a pair needs at least one label")

        keys = [lbl.span_key for lbl in self.labels]
        if len(set(keys)) != len(keys):
            raise ValueError(
                "duplicate labeled span: one span carries exactly one gain, or "
                "scoring would credit the same evidence twice"
            )

        ordered = tuple(sorted(self.labels, key=lambda lbl: lbl.span_key))
        if ordered != self.labels:
            # Sorted rather than rejected: label order is not information, and
            # the set hash is taken over the serialized pair, so the order has
            # to be a function of the labels rather than of data entry.
            object.__setattr__(self, "labels", ordered)
        return self

    @model_validator(mode="after")
    def _must_carry_at_least_one_relevant_span(self) -> Self:
        if not any(lbl.is_relevant for lbl in self.labels):
            raise ValueError(
                f"no label reaches gain >= {MIN_RELEVANT_GAIN}, so Recall would "
                f"exclude this query from the mean entirely; it contributes "
                f"nothing but a footnote"
            )
        return self

    @property
    def relevant_labels(self) -> tuple[RelevanceLabel, ...]:
        return tuple(lbl for lbl in self.labels if lbl.is_relevant)

    def identity_payload(self) -> dict[str, object]:
        """What this pair *is*, for hashing.

        Review timestamps and durations are excluded deliberately: re-reviewing
        an unchanged pair must not invalidate every committed baseline. Who
        reviewed it and whether they edited it are kept, because those change
        what the record claims.
        """
        payload = self.model_dump(mode="json")
        provenance = dict(payload["provenance"])
        provenance.pop("reviewed_at", None)
        provenance.pop("review_seconds", None)
        payload["provenance"] = provenance
        return payload


class GoldenSet(FrozenModel):
    """The reviewed set, and its content address.

    The hash is what the gate compares run to run. A regression "fixed" by
    deleting the queries it fails changes this value, and the gate hard-fails
    on that rather than reporting an improvement (ADR-0010).
    """

    pairs: tuple[GoldenPair, ...] = ()

    @model_validator(mode="after")
    def _pairs_must_be_unique_and_ordered(self) -> Self:
        ids = [p.query_id for p in self.pairs]
        if len(set(ids)) != len(ids):
            duplicate = next(qid for qid, n in Counter(ids).items() if n > 1)
            raise ValueError(f"duplicate query_id {duplicate!r}")

        texts = [normalize_query(p.query) for p in self.pairs]
        if len(set(texts)) != len(texts):
            duplicate = next(text for text, n in Counter(texts).items() if n > 1)
            raise ValueError(
                f"duplicate query text {duplicate!r}: two spellings of one "
                f"question are a single data point reported as two"
            )

        ordered = tuple(sorted(self.pairs, key=lambda p: p.query_id))
        if ordered != self.pairs:
            object.__setattr__(self, "pairs", ordered)
        return self

    @property
    def golden_set_hash(self) -> str:
        """Content address of the reviewed set."""
        payload = [pair.identity_payload() for pair in self.pairs]
        digest = hashlib.sha256(canonical_json({"pairs": payload}).encode("utf-8")).hexdigest()
        return f"sha256:{digest}"

    def counts_by_category(self) -> dict[str, int]:
        """Query count per category, including categories with none."""
        counts: dict[str, int] = dict.fromkeys(CATEGORIES, 0)
        for pair in self.pairs:
            counts[pair.category] += 1
        return counts

    def counts_by_origin(self) -> dict[str, int]:
        counts = {"human": 0, "llm": 0}
        for pair in self.pairs:
            counts[pair.provenance.origin] += 1
        return counts
