"""A five-document corpus the whole pipeline can be developed against.

The real corpus is 150 opinions and an 8.5 MB embedding cache. Developing
against it means every test needs the committed cache to be current, which
couples the test suite to an artifact that is regenerated by hand.

So the pipeline is exercised end to end against this instead: five invented
opinions, the *real* vendored tokenizer, and a deterministic stand-in
embedder. Everything except the weights is the production code path.

The opinions are fictional. The case names, reporters and holdings are
invented, and are written to be plainly so -- a test fixture that reads like
real precedent is a citation waiting to happen.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from typing import Final

import numpy as np

from groundtruth.config.models import (
    ChunkingConfig,
    EmbeddingConfig,
    FusionConfig,
    LexicalConfig,
    RetrievalConfig,
)
from groundtruth.corpus.models import Document

#: Small enough that a ~250-word opinion produces two or three chunks, so
#: multi-chunk documents are actually exercised.
MINI_CHUNK_SIZE: Final[int] = 128
MINI_CHUNK_OVERLAP: Final[int] = 16

MINI_MODEL_ID: Final[str] = "test-org/hashing-embedder"
MINI_REVISION: Final[str] = "0000000000000000000000000000000000000000"
#: Wider than it needs to be for five documents. At 64 buckets the hashing
#: embedder below collides often enough that ranking assertions would be
#: testing the collision pattern rather than the retriever.
MINI_DIMENSION: Final[int] = 256

SUMMARY_JUDGMENT = """
Purcell v. Braddock Mills, 12 Fict. 441 (Hypo. Ct. App. 1994)

The question presented is the standard a trial court applies on a motion for
summary judgment. Summary judgment is appropriate only where there is no
genuine dispute as to any material fact and the moving party is entitled to
judgment as a matter of law. A fact is material if it could affect the outcome
of the suit under the governing law, and a dispute is genuine if the evidence
would permit a reasonable factfinder to return a verdict for the nonmoving
party.

The court does not weigh the evidence or make credibility determinations at
this stage. All justifiable inferences are drawn in favor of the nonmoving
party. The moving party bears the initial burden of identifying those portions
of the record which it believes demonstrate the absence of a genuine dispute.
Once that burden is met, the nonmoving party may not rest upon mere allegations
but must set forth specific facts showing a genuine issue for trial.

Applying that standard here, the record discloses a genuine dispute regarding
the date on which the defendant received notice of the defect. The grant of
summary judgment is therefore reversed and the matter is remanded for trial.
"""

PERSONAL_JURISDICTION = """
Ansel Freightways, Inc. v. Odell Components Ltd., 31 Fict. 208 (Hypo. 2001)

A court may exercise personal jurisdiction over a nonresident defendant only
where the defendant has established minimum contacts with the forum state such
that maintenance of the suit does not offend traditional notions of fair play
and substantial justice. The inquiry focuses on the relationship among the
defendant, the forum, and the litigation.

Purposeful availment is the touchstone. A defendant who deliberately reaches
into a forum to conduct business there may fairly be haled into its courts.
Contacts that are random, fortuitous, or attenuated, or that result solely from
the unilateral activity of a third party, will not support jurisdiction.

The defendant here manufactured components abroad and sold them to a
distributor with no knowledge of where the distributor resold them. Mere
awareness that a product may enter the stream of commerce and reach the forum
is not, without more, an act purposefully directed toward the forum. Because
the defendant did not purposefully avail itself of the privilege of conducting
activities in this state, the motion to dismiss for lack of personal
jurisdiction is granted.
"""

QUALIFIED_IMMUNITY = """
Rothgery Estate v. Village of Calder Point, 44 Fict. 17 (Hypo. Ct. App. 2008)

Qualified immunity shields a government official performing a discretionary
function from civil damages liability unless the official violated a statutory
or constitutional right that was clearly established at the time of the
challenged conduct. The doctrine gives officials breathing room to make
reasonable but mistaken judgments about open legal questions.

A right is clearly established when its contours are sufficiently definite that
any reasonable official in the defendant's position would have understood that
what the official was doing violated that right. This does not require a case
directly on point, but existing precedent must have placed the question beyond
debate. Courts are not to define clearly established law at a high level of
generality.

The officer here entered a fenced side yard without a warrant in response to a
noise complaint. No decision of this court or of any court of appeals had
addressed whether a noise complaint alone justifies such an entry. Because the
law was not clearly established, the officer is entitled to qualified immunity,
and the judgment below is affirmed.
"""

VEHICLE_SEARCH = """
Hollings v. State of Marren, 58 Fict. 903 (Hypo. 2013)

We consider whether the warrantless search of the passenger compartment of an
automobile incident to the arrest of a recent occupant was reasonable under the
Fourth Amendment. Police may search a vehicle incident to arrest only if the
arrestee is within reaching distance of the passenger compartment at the time
of the search, or it is reasonable to believe the vehicle contains evidence of
the offense of arrest.

The rationale for the search incident to arrest exception is officer safety and
the preservation of evidence. Neither justification is present where the
arrestee has been handcuffed, removed from the vehicle, and secured in the back
of a patrol car, and where the offense of arrest is a traffic violation for
which no physical evidence could be found in the vehicle.

Here the defendant was arrested for driving with a suspended license and was
secured before the search began. The search of the passenger compartment cannot
be justified as incident to arrest, and the evidence recovered must be
suppressed.
"""

CONTRACT_FORMATION = """
Teague Orchards v. Sandoval Packing Co., 7 Fict. 62 (Hypo. Ct. App. 1989)

The dispositive issue is whether the parties formed an enforceable contract. A
contract requires an offer, an acceptance, and consideration. Consideration is
a bargained-for exchange in which each party incurs a legal detriment or
confers a legal benefit. A promise to perform an act one is already legally
obligated to perform is not consideration and will not support a contract.

An offer is a manifestation of willingness to enter a bargain so made as to
justify another person in understanding that assent to that bargain is invited
and will conclude it. Acceptance must be unequivocal; a purported acceptance
that adds or varies a material term operates as a counteroffer and terminates
the power of acceptance.

The buyer's response here added a delivery deadline absent from the seller's
offer. That term was material, and the response therefore operated as a
counteroffer, which the seller never accepted. No contract was formed, and the
award of expectation damages is reversed.
"""


def mini_documents() -> tuple[Document, ...]:
    """The five invented opinions, in ``doc_id`` order."""
    raw = {
        "mini-001": SUMMARY_JUDGMENT,
        "mini-002": PERSONAL_JURISDICTION,
        "mini-003": QUALIFIED_IMMUNITY,
        "mini-004": VEHICLE_SEARCH,
        "mini-005": CONTRACT_FORMATION,
    }
    return tuple(
        Document(doc_id=doc_id, text=text.strip(), court="Hypothetical", date_filed="1990-01-01")
        for doc_id, text in sorted(raw.items())
    )


def mini_config(
    *,
    name: str = "mini_dense",
    retrieval_mode: str = "dense",
    top_k: int = 5,
    dense_top_n: int = 20,
    lexical_top_n: int = 20,
    query_prefix: str = "",
    dimension: int = MINI_DIMENSION,
) -> RetrievalConfig:
    """A configuration wired to the vendored tokenizer and the stand-in model."""
    lexical = (
        LexicalConfig(backend="bm25", top_n=lexical_top_n) if retrieval_mode == "hybrid" else None
    )
    return RetrievalConfig(
        name=name,
        retrieval_mode=retrieval_mode,  # type: ignore[arg-type]
        top_k=top_k,
        dense_top_n=dense_top_n,
        chunking=ChunkingConfig(
            chunk_size=MINI_CHUNK_SIZE,
            chunk_overlap=MINI_CHUNK_OVERLAP,
            # The real vendored tokenizer: chunk boundaries in the mini corpus
            # are produced by exactly the code path the real corpus uses.
            tokenizer_id="BAAI/bge-small-en-v1.5",
        ),
        embedding=EmbeddingConfig(
            model_id=MINI_MODEL_ID,
            revision=MINI_REVISION,
            dimension=dimension,
            normalize=True,
            query_prefix=query_prefix,
        ),
        lexical=lexical,
        fusion=FusionConfig() if retrieval_mode == "hybrid" else None,
    )


_TOKEN_PATTERN = re.compile(r"[^\W_]+", re.UNICODE)

#: Ignored by the stand-in embedder below -- and *only* by it. The production
#: BM25 index deliberately has no stopword list (its IDF term does that job
#: properly); this one has no IDF, so without a stoplist a natural-language
#: query like "when is an officer entitled to qualified immunity" is dominated
#: by its function words and ranks documents by how chatty they are. A real
#: sentence encoder does not have that failure mode, so a fixture that did
#: would be testing the fixture.
_STOPWORDS = frozenset(
    """a an and are as at be by for from has have in is it its of on or that the
    their this to was were when whether which with within would shall may must
    not no any all such under upon""".split()
)


class HashingEmbedder:
    """A deterministic stand-in for a sentence encoder.

    Each token is hashed into one of ``dimension`` buckets and the resulting
    bag-of-buckets vector is L2-normalized. That is a real (if crude) retrieval
    model: documents sharing vocabulary with the query score higher, so an
    end-to-end test can assert *retrieval behaviour* rather than merely
    asserting that the plumbing runs.

    A random or hash-of-the-whole-string fake would only prove the wiring, and
    would make every ranking assertion meaningless.

    ``blake2b`` rather than ``hash()``: Python salts string hashing per
    process, so ``hash()`` would make the fixture non-reproducible across runs.
    """

    model_id = MINI_MODEL_ID
    revision = MINI_REVISION
    dimension = MINI_DIMENSION
    normalize = True

    def __init__(self) -> None:
        #: Every string this embedder was asked for, in order. Lets a test
        #: assert the query prefix reached the model.
        self.seen: list[str] = []

    @staticmethod
    def _bucket(token: str) -> int:
        from hashlib import blake2b

        return int.from_bytes(blake2b(token.encode("utf-8"), digest_size=4).digest(), "big") % (
            MINI_DIMENSION
        )

    def embed(self, texts: Sequence[str]) -> np.ndarray:
        self.seen.extend(texts)
        out = np.zeros((len(texts), MINI_DIMENSION), dtype=np.float32)
        for row, text in enumerate(texts):
            for token in _TOKEN_PATTERN.findall(text.lower()):
                if token in _STOPWORDS:
                    continue
                out[row, self._bucket(token)] += 1.0
            norm = float(np.linalg.norm(out[row]))
            if norm:
                out[row] /= norm
            else:
                # A chunk with no word characters would otherwise be a zero
                # vector, which has no defined cosine similarity.
                out[row, 0] = 1.0
        return out
